/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package antiSpamFilter.gui;

import antiSpamFilter.AntiSpamFilter;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;

/**
 * This is our take on a simple Graphical User Interface
 * This layout was designed and adjusted at the start of the project via group meetings
 *
 * @author Carlos Rafael Fernandes
 *
 */
public class GUI extends javax.swing.JFrame {

    /**
     * @
     */
    public GUI() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        RulesPath.setText(System.getProperty("user.dir")+"\\AntiSpamConfigurationForProfessionalMailbox\\rules.cf");
        OutputPath.setText(System.getProperty("user.dir")+"\\experimentBaseDirectory");

        TableManual.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                },
                new String [] {"Rules", "Weight"}
        ));
        TableManual.getTableHeader().setReorderingAllowed(false);
        TableAuto.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null},
                },
                new String [] {"Rules", "Weight"}
        ));
        TableAuto.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModeRadioGroup = new javax.swing.ButtonGroup();
        ProgressBar = new javax.swing.JProgressBar();
        Start = new javax.swing.JToggleButton();
        ManualRadio = new javax.swing.JRadioButton();
        AutoRadio = new javax.swing.JRadioButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ManualMode = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableManual = new JTable(){
            @Override
            public boolean isCellEditable(int row, int column){
                return column != 0;
            }
        }
        ;
        ManualSave = new javax.swing.JButton();
        GenerateRandom = new javax.swing.JButton();
        AutoMode = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableAuto = new JTable(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }
        ;
        AutoSave = new javax.swing.JButton();
        ConsolePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Console = new javax.swing.JTextArea();
        PathPanel = new javax.swing.JPanel();
        InputPanel = new javax.swing.JPanel();
        ChangeSpamPath = new javax.swing.JButton();
        ChangeHamPath = new javax.swing.JButton();
        ChangeRulesPath = new javax.swing.JButton();
        RulesPath = new javax.swing.JTextField();
        HamPath = new javax.swing.JTextField();
        SpamPath = new javax.swing.JTextField();
        SpamJLabel = new javax.swing.JLabel();
        HamJLabel = new javax.swing.JLabel();
        RulesJLabel = new javax.swing.JLabel();
        OutputPanel = new javax.swing.JPanel();
        OutputPath = new javax.swing.JTextField();
        ChangeOutputPath = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anti Spam Filter");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        Start.setText("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        ModeRadioGroup.add(ManualRadio);
        ManualRadio.setText("Manual");
        ManualRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManualRadioActionPerformed(evt);
            }
        });

        ModeRadioGroup.add(AutoRadio);
        AutoRadio.setText("Auto");

        TableManual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TableManual);

        ManualSave.setText("Save Config");

        GenerateRandom.setText("Generate Ramdom Configuration");

        javax.swing.GroupLayout ManualModeLayout = new javax.swing.GroupLayout(ManualMode);
        ManualMode.setLayout(ManualModeLayout);
        ManualModeLayout.setHorizontalGroup(
            ManualModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManualModeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManualModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManualModeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(GenerateRandom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ManualSave)))
                .addContainerGap())
        );
        ManualModeLayout.setVerticalGroup(
            ManualModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManualModeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ManualModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManualSave)
                    .addComponent(GenerateRandom))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manual Mode", ManualMode);

        TableAuto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(TableAuto);

        AutoSave.setText("Save Config");

        javax.swing.GroupLayout AutoModeLayout = new javax.swing.GroupLayout(AutoMode);
        AutoMode.setLayout(AutoModeLayout);
        AutoModeLayout.setHorizontalGroup(
            AutoModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AutoModeLayout.createSequentialGroup()
                .addContainerGap(674, Short.MAX_VALUE)
                .addComponent(AutoSave)
                .addContainerGap())
            .addGroup(AutoModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AutoModeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4)
                    .addContainerGap()))
        );
        AutoModeLayout.setVerticalGroup(
            AutoModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AutoModeLayout.createSequentialGroup()
                .addContainerGap(454, Short.MAX_VALUE)
                .addComponent(AutoSave, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(AutoModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(AutoModeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addGap(40, 40, 40)))
        );

        jTabbedPane1.addTab("Auto Mode", AutoMode);

        Console.setEditable(false);
        Console.setColumns(20);
        Console.setRows(5);
        jScrollPane1.setViewportView(Console);

        javax.swing.GroupLayout ConsolePanelLayout = new javax.swing.GroupLayout(ConsolePanel);
        ConsolePanel.setLayout(ConsolePanelLayout);
        ConsolePanelLayout.setHorizontalGroup(
            ConsolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsolePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addContainerGap())
        );
        ConsolePanelLayout.setVerticalGroup(
            ConsolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsolePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Console", ConsolePanel);

        InputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Files"));

        ChangeSpamPath.setText("...");
        ChangeSpamPath.setMaximumSize(new java.awt.Dimension(45, 20));
        ChangeSpamPath.setMinimumSize(new java.awt.Dimension(45, 20));
        ChangeSpamPath.setPreferredSize(new java.awt.Dimension(45, 20));
        ChangeSpamPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeSpamPathActionPerformed(evt);
            }
        });

        ChangeHamPath.setText("...");
        ChangeHamPath.setMaximumSize(new java.awt.Dimension(45, 20));
        ChangeHamPath.setMinimumSize(new java.awt.Dimension(45, 20));
        ChangeHamPath.setPreferredSize(new java.awt.Dimension(45, 20));
        ChangeHamPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeHamPathActionPerformed(evt);
            }
        });

        ChangeRulesPath.setText("...");
        ChangeRulesPath.setMaximumSize(new java.awt.Dimension(45, 20));
        ChangeRulesPath.setMinimumSize(new java.awt.Dimension(45, 20));
        ChangeRulesPath.setPreferredSize(new java.awt.Dimension(45, 20));
        ChangeRulesPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeRulesPathActionPerformed(evt);
            }
        });

        RulesPath.setEditable(false);

        HamPath.setEditable(false);

        SpamPath.setEditable(false);

        SpamJLabel.setText("spam.log");

        HamJLabel.setText("ham.log");

        RulesJLabel.setText("rules.cf");

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RulesJLabel)
                    .addComponent(SpamJLabel)
                    .addComponent(HamJLabel))
                .addGap(18, 18, 18)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RulesPath, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                    .addComponent(HamPath)
                    .addComponent(SpamPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChangeRulesPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeHamPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeSpamPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RulesJLabel)
                    .addComponent(RulesPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeRulesPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HamJLabel)
                    .addComponent(HamPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeHamPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpamJLabel)
                    .addComponent(SpamPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeSpamPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OutputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Output Files"));

        OutputPath.setEditable(false);

        ChangeOutputPath.setText("...");
        ChangeOutputPath.setMaximumSize(new java.awt.Dimension(45, 20));
        ChangeOutputPath.setMinimumSize(new java.awt.Dimension(45, 20));
        ChangeOutputPath.setPreferredSize(new java.awt.Dimension(45, 20));
        ChangeOutputPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeOutputPathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OutputPanelLayout = new javax.swing.GroupLayout(OutputPanel);
        OutputPanel.setLayout(OutputPanelLayout);
        OutputPanelLayout.setHorizontalGroup(
            OutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutputPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(OutputPath, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ChangeOutputPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(388, 388, 388))
        );
        OutputPanelLayout.setVerticalGroup(
            OutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OutputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(OutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OutputPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeOutputPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout PathPanelLayout = new javax.swing.GroupLayout(PathPanel);
        PathPanel.setLayout(PathPanelLayout);
        PathPanelLayout.setHorizontalGroup(
            PathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 775, Short.MAX_VALUE)
            .addComponent(OutputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 775, Short.MAX_VALUE)
        );
        PathPanelLayout.setVerticalGroup(
            PathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PathPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OutputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Path Config", PathPanel);

        jTabbedPane1.setSelectedIndex(3);

        jLabel1.setText("0");

        jLabel2.setText("FN:");

        jLabel4.setText("0");

        jLabel5.setText("FP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ManualRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AutoRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Start)
                    .addComponent(ManualRadio)
                    .addComponent(AutoRadio)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManualRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManualRadioActionPerformed

    private void ChangeRulesPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeRulesPathActionPerformed
        JFileChooser path_chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CF Files", "cf");
        path_chooser.setFileFilter(filter);
        int returnVal = path_chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            RulesPath.setText(path_chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_ChangeRulesPathActionPerformed

    private void ChangeHamPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeHamPathActionPerformed
        JFileChooser path_chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("LOG File", "log");
        path_chooser.setFileFilter(filter);
        int returnVal = path_chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            HamPath.setText(path_chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_ChangeHamPathActionPerformed

    private void ChangeSpamPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeSpamPathActionPerformed
        JFileChooser path_chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("LOG File", "log");
        path_chooser.setFileFilter(filter);
        int returnVal = path_chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            SpamPath.setText(path_chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_ChangeSpamPathActionPerformed

    private void ChangeOutputPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeOutputPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeOutputPathActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        if(ManualRadio.isSelected() || AutoRadio.isSelected()) {
            if (AutoRadio.isSelected())
                AntiSpamFilter.getInstance().runAuto();
            else
                AntiSpamFilter.getInstance().runManual();
        }
        else{
            int VIBRATION_LENGTH = 10;
            int VIBRATION_VELOCITY = 2;
            try {
                Runnable runnable = (Runnable) Toolkit.getDefaultToolkit().getDesktopProperty("win.sound.exclamation");
                if (runnable != null) runnable.run();
                int originalX = this.getLocationOnScreen().x;
                int originalY = this.getLocationOnScreen().y;
                for(int i = 0; i < VIBRATION_LENGTH; i++) {
                    Thread.sleep(10);
                    this.setLocation(originalX + VIBRATION_VELOCITY, originalY);
                    Thread.sleep(10);
                    this.setLocation(originalX - VIBRATION_VELOCITY, originalY);
                    Thread.sleep(10);
                    this.setLocation(originalX, originalY);
                }
            }
            catch (Exception err) {
                err.printStackTrace();
            }
        }
    }//GEN-LAST:event_StartActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AutoMode;
    private javax.swing.JRadioButton AutoRadio;
    private javax.swing.JButton AutoSave;
    private javax.swing.JButton ChangeHamPath;
    private javax.swing.JButton ChangeOutputPath;
    private javax.swing.JButton ChangeRulesPath;
    private javax.swing.JButton ChangeSpamPath;
    private javax.swing.JTextArea Console;
    private javax.swing.JPanel ConsolePanel;
    private javax.swing.JButton GenerateRandom;
    private javax.swing.JLabel HamJLabel;
    private javax.swing.JTextField HamPath;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JPanel ManualMode;
    private javax.swing.JRadioButton ManualRadio;
    private javax.swing.JButton ManualSave;
    private javax.swing.ButtonGroup ModeRadioGroup;
    private javax.swing.JPanel OutputPanel;
    private javax.swing.JTextField OutputPath;
    private javax.swing.JPanel PathPanel;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel RulesJLabel;
    private javax.swing.JTextField RulesPath;
    private javax.swing.JLabel SpamJLabel;
    private javax.swing.JTextField SpamPath;
    private javax.swing.JToggleButton Start;
    private javax.swing.JTable TableAuto;
    private javax.swing.JTable TableManual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public String getRulesPath(){
        return RulesPath.getText();
    }

    public String getHamsPath(){
        return HamPath.getText();
    }

    public String getSpamPath(){
        return SpamPath.getText();
    }

}
