/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package antiSpamFilter.gui;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * This is our take on a simple Graphical User Interface
 * This layout was designed and adjusted at the start of the project via group meetings
 *
 * @author Carlos Rafael Fernandes
 *
 */
public class GUI extends javax.swing.JFrame {

    /**
     * @
     */
    public GUI() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModeRadioGroup = new javax.swing.ButtonGroup();
        ProgressBar = new javax.swing.JProgressBar();
        Start = new javax.swing.JToggleButton();
        ManualRadio = new javax.swing.JRadioButton();
        AutoRadio = new javax.swing.JRadioButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ConsolePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        PathPanel = new javax.swing.JPanel();
        RulesJLabel = new javax.swing.JLabel();
        HamJLabel = new javax.swing.JLabel();
        SpamJLabel = new javax.swing.JLabel();
        RulesPath = new javax.swing.JTextField();
        HamPath = new javax.swing.JTextField();
        SpamPath = new javax.swing.JTextField();
        ChangeRulesPath = new javax.swing.JButton();
        ChangeHamPath = new javax.swing.JButton();
        ChangeSpamPath = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Anti Spam Filter");
        setResizable(false);

        Start.setText("Start");

        ModeRadioGroup.add(ManualRadio);
        ManualRadio.setText("Manual");
        ManualRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManualRadioActionPerformed(evt);
            }
        });

        ModeRadioGroup.add(AutoRadio);
        AutoRadio.setText("Auto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Manual Mode", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Auto Mode", jPanel3);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout ConsolePanelLayout = new javax.swing.GroupLayout(ConsolePanel);
        ConsolePanel.setLayout(ConsolePanelLayout);
        ConsolePanelLayout.setHorizontalGroup(
            ConsolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsolePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addContainerGap())
        );
        ConsolePanelLayout.setVerticalGroup(
            ConsolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsolePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Console", ConsolePanel);

        RulesJLabel.setText("rules.cf");

        HamJLabel.setText("ham.log");

        SpamJLabel.setText("spam.log");

        RulesPath.setEditable(false);

        HamPath.setEditable(false);

        SpamPath.setEditable(false);

        ChangeRulesPath.setText("...");
        ChangeRulesPath.setMaximumSize(new java.awt.Dimension(45, 20));
        ChangeRulesPath.setMinimumSize(new java.awt.Dimension(45, 20));
        ChangeRulesPath.setPreferredSize(new java.awt.Dimension(45, 20));
        ChangeRulesPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeRulesPathActionPerformed(evt);
            }
        });

        ChangeHamPath.setText("...");
        ChangeHamPath.setMaximumSize(new java.awt.Dimension(45, 20));
        ChangeHamPath.setMinimumSize(new java.awt.Dimension(45, 20));
        ChangeHamPath.setPreferredSize(new java.awt.Dimension(45, 20));
        ChangeHamPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeHamPathActionPerformed(evt);
            }
        });

        ChangeSpamPath.setText("...");
        ChangeSpamPath.setMaximumSize(new java.awt.Dimension(45, 20));
        ChangeSpamPath.setMinimumSize(new java.awt.Dimension(45, 20));
        ChangeSpamPath.setPreferredSize(new java.awt.Dimension(45, 20));
        ChangeSpamPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeSpamPathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PathPanelLayout = new javax.swing.GroupLayout(PathPanel);
        PathPanel.setLayout(PathPanelLayout);
        PathPanelLayout.setHorizontalGroup(
            PathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PathPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RulesJLabel)
                    .addComponent(SpamJLabel)
                    .addComponent(HamJLabel))
                .addGap(18, 18, 18)
                .addGroup(PathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HamPath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(RulesPath, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SpamPath))
                .addGap(3, 3, 3)
                .addGroup(PathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChangeRulesPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeHamPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeSpamPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        PathPanelLayout.setVerticalGroup(
            PathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PathPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RulesJLabel)
                    .addComponent(RulesPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeRulesPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HamJLabel)
                    .addComponent(HamPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeHamPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpamJLabel)
                    .addComponent(SpamPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChangeSpamPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(383, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Path Config", PathPanel);

        jTabbedPane1.setSelectedIndex(3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ManualRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AutoRadio)
                        .addGap(510, 510, 510)
                        .addComponent(Start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Start)
                    .addComponent(ManualRadio)
                    .addComponent(AutoRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManualRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManualRadioActionPerformed

    private void ChangeRulesPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeRulesPathActionPerformed
        JFileChooser path_chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CF Files", "cf");
        path_chooser.setFileFilter(filter);
        int returnVal = path_chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            RulesPath.setText(path_chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_ChangeRulesPathActionPerformed

    private void ChangeHamPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeHamPathActionPerformed
        JFileChooser path_chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("LOG File", "log");
        path_chooser.setFileFilter(filter);
        int returnVal = path_chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            HamPath.setText(path_chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_ChangeHamPathActionPerformed

    private void ChangeSpamPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeSpamPathActionPerformed
        JFileChooser path_chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("LOG File", "log");
        path_chooser.setFileFilter(filter);
        int returnVal = path_chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            SpamPath.setText(path_chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_ChangeSpamPathActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AutoRadio;
    private javax.swing.JButton ChangeHamPath;
    private javax.swing.JButton ChangeRulesPath;
    private javax.swing.JButton ChangeSpamPath;
    private javax.swing.JPanel ConsolePanel;
    private javax.swing.JLabel HamJLabel;
    private javax.swing.JTextField HamPath;
    private javax.swing.JRadioButton ManualRadio;
    private javax.swing.ButtonGroup ModeRadioGroup;
    private javax.swing.JPanel PathPanel;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel RulesJLabel;
    private javax.swing.JTextField RulesPath;
    private javax.swing.JLabel SpamJLabel;
    private javax.swing.JTextField SpamPath;
    private javax.swing.JToggleButton Start;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
